### ISSUE TITLE
Not able to run `docker build` on a M1 Mac

### ISSUE THREAD

**Issue by reimertz** [aws-samples/cost-effective-aws-deployment-of-comfyui#1]
Hi there and thanks for this starter project. 

I've been going through the readme and hit a snag at trying to build the docker image.

It seems it's related to installing pip dependencies.

Here is the error log

```
➜  cost-effective-aws-deployment-of-comfyui git:(main) ✗ docker build --platform linux/amd64 .
[+] Building 55.3s (13/15)                                          docker:desktop-linux
 => [internal] load build definition from dockerfile                                0.0s
 => => transferring dockerfile: 2.13kB                                              0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:12.3.1-runtime-ubuntu22.04   1.0s
 => [internal] load .dockerignore                                                   0.0s
 => => transferring context: 2B                                                     0.0s
 => [internal] load build context                                                   0.0s
 => => transferring context: 93B                                                    0.0s
 => [ 1/11] FROM docker.io/nvidia/cuda:12.3.1-runtime-ubuntu22.04@sha256:acb1709dc  0.0s
 => CACHED [ 2/11] RUN apt-get update && apt-get install -y     git     make build  0.0s
 => CACHED [ 3/11] RUN useradd -m -u 1000 user                                      0.0s
 => CACHED [ 4/11] RUN curl https://pyenv.run | bash                                0.0s
 => CACHED [ 5/11] RUN pyenv install 3.10.12 &&     pyenv global 3.10.12 &&     py  0.0s
 => CACHED [ 6/11] WORKDIR /home/user/opt/ComfyUI                                   0.0s
 => CACHED [ 7/11] RUN git clone --depth 1 https://github.com/comfyanonymous/Comfy  0.0s
 => CACHED [ 8/11] RUN python -m venv /home/user/opt/ComfyUI/.venv                  0.0s
 => ERROR [ 9/11] RUN . /home/user/opt/ComfyUI/.venv/bin/activate && pip install   54.2s
------
 > [ 9/11] RUN . /home/user/opt/ComfyUI/.venv/bin/activate && pip install xformers!=0.0.18 --no-cache-dir -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu121:
1.204 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
2.100 Collecting xformers!=0.0.18
2.118   Downloading https://download.pytorch.org/whl/cu121/xformers-0.0.25-cp310-cp310-manylinux2014_x86_64.whl (222.5 MB)
4.239      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.5/222.5 MB 102.7 MB/s eta 0:00:00
5.666 Collecting torch
5.679   Downloading https://download.pytorch.org/whl/cu121/torch-2.2.1%2Bcu121-cp310-cp310-linux_x86_64.whl (757.3 MB)
13.14      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.3/757.3 MB 129.0 MB/s eta 0:00:00
16.02 Collecting torchsde
16.20   Downloading torchsde-0.2.6-py3-none-any.whl (61 kB)
16.23      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 1.8 MB/s eta 0:00:00
16.98 Collecting torchvision
17.00   Downloading https://download.pytorch.org/whl/cu121/torchvision-0.17.1%2Bcu121-cp310-cp310-linux_x86_64.whl (7.0 MB)
17.09      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 74.6 MB/s eta 0:00:00
17.63 Collecting einops
17.66   Downloading einops-0.7.0-py3-none-any.whl (44 kB)
17.67      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 88.0 MB/s eta 0:00:00
18.32 Collecting transformers>=4.25.1
18.35   Downloading transformers-4.38.2-py3-none-any.whl (8.5 MB)
18.58      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 38.1 MB/s eta 0:00:00
19.37 Collecting safetensors>=0.3.0
19.40   Downloading safetensors-0.4.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
19.44      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 34.0 MB/s eta 0:00:00
20.54 Collecting aiohttp
20.56   Downloading aiohttp-3.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
20.60      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 33.2 MB/s eta 0:00:00
21.20 Collecting pyyaml
21.23   Downloading PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (705 kB)
21.25      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 705.5/705.5 kB 41.6 MB/s eta 0:00:00
22.18 Collecting Pillow
22.20   Downloading https://download.pytorch.org/whl/pillow-10.2.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
22.26      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 70.5 MB/s eta 0:00:00
22.99 Collecting scipy
23.05   Downloading scipy-1.12.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.4 MB)
24.22      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.4/38.4 MB 33.7 MB/s eta 0:00:00
24.93 Collecting tqdm
24.95   Downloading tqdm-4.66.2-py3-none-any.whl (78 kB)
24.95      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 85.9 MB/s eta 0:00:00
25.64 Collecting psutil
25.67   Downloading psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
25.67      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 kB 121.6 MB/s eta 0:00:00
26.24 Collecting kornia>=0.7.1
26.27   Downloading kornia-0.7.2-py2.py3-none-any.whl (825 kB)
26.30      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 825.4/825.4 kB 42.7 MB/s eta 0:00:00
27.25 Collecting numpy
27.27   Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
27.80      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 35.3 MB/s eta 0:00:00
28.48 Collecting filelock
28.50   Downloading filelock-3.13.1-py3-none-any.whl (11 kB)
28.94 Collecting nvidia-cuda-runtime-cu12==12.1.105
28.96   Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
28.98      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 43.0 MB/s eta 0:00:00
29.51 Collecting nvidia-cuda-cupti-cu12==12.1.105
29.53   Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
29.70      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 115.1 MB/s eta 0:00:00
30.18 Collecting nvidia-curand-cu12==10.3.2.106
30.20   Downloading https://download.pytorch.org/whl/cu121/nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
31.07      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 57.2 MB/s eta 0:00:00
31.67 Collecting nvidia-cusolver-cu12==11.4.5.107
32.05   Downloading https://download.pytorch.org/whl/cu121/nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
33.70      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 80.1 MB/s eta 0:00:00
34.60 Collecting nvidia-nccl-cu12==2.19.3
34.61   Downloading https://download.pytorch.org/whl/cu121/nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
36.09      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 119.9 MB/s eta 0:00:00
37.12 Collecting triton==2.2.0
37.14   Downloading https://download.pytorch.org/whl/triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (167.9 MB)
53.17      ━━━━━━━━━━━━━━━━━━━━━━━━              109.3/167.9 MB 163.9 MB/s eta 0:00:01
53.18 ERROR: Exception:
53.18 Traceback (most recent call last):
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
53.18     yield
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
53.18     data = self._fp_read(amt) if not fp_closed else b""
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
53.18     return self._fp.read(amt) if amt is not None else self._fp.read()
53.18   File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/http/client.py", line 466, in read
53.18     s = self.fp.read(amt)
53.18   File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/socket.py", line 705, in readinto
53.18     return self._sock.recv_into(b)
53.18   File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/ssl.py", line 1274, in recv_into
53.18     return self.read(nbytes, buffer)
53.18   File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/ssl.py", line 1130, in read
53.18     return self._sslobj.read(len, buffer)
53.18 TimeoutError: The read operation timed out
53.18
53.18 During handling of the above exception, another exception occurred:
53.18
53.18 Traceback (most recent call last):
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
53.18     status = run_func(*args)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
53.18     return func(self, options, args)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 419, in run
53.18     requirement_set = resolver.resolve(
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
53.18     result = self._result = resolver.resolve(
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
53.18     state = resolution.resolve(requirements, max_rounds=max_rounds)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
53.18     failure_causes = self._attempt_to_pin_criterion(name)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
53.18     criteria = self._get_updated_criteria(candidate)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
53.18     self._add_to_criteria(criteria, requirement, parent=candidate)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
53.18     if not criterion.candidates:
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
53.18     return bool(self._sequence)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
53.18     return any(self)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
53.18     return (c for c in iterator if id(c) not in self._incompatible_ids)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
53.18     candidate = func()
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
53.18     self._link_candidate_cache[link] = LinkCandidate(
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
53.18     super().__init__(
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
53.18     self.dist = self._prepare()
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
53.18     dist = self._prepare_distribution()
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
53.18     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
53.18     return self._prepare_linked_requirement(req, parallel_builds)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
53.18     local_file = unpack_url(
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
53.18     file = get_http_url(
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
53.18     from_path, content_type = download(link, temp_dir.path)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
53.18     for chunk in chunks:
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
53.18     for chunk in iterable:
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
53.18     for chunk in response.raw.stream(
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
53.18     data = self.read(amt=amt, decode_content=decode_content)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
53.18     with self._error_catcher():
53.18   File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/contextlib.py", line 153, in __exit__
53.18     self.gen.throw(typ, value, traceback)
53.18   File "/home/user/opt/ComfyUI/.venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
53.18     raise ReadTimeoutError(self._pool, None, "Read timed out.")
53.18 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Read timed out.
53.92
53.92 [notice] A new release of pip is available: 23.0.1 -> 24.0
53.92 [notice] To update, run: pip install --upgrade pip
------
dockerfile:41
--------------------
  39 |     RUN python -m venv $TEMP_VENV_PATH
  40 |
  41 | >>> RUN . $TEMP_VENV_PATH/bin/activate && pip install xformers!=0.0.18 --no-cache-dir -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu121
  42 |
  43 |     # Clone ComfyUI-Manager and install its requirements
--------------------
ERROR: failed to solve: process "/bin/sh -c . $TEMP_VENV_PATH/bin/activate && pip install xformers!=0.0.18 --no-cache-dir -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu121" did not complete successfully: exit code: 2
```

Any idea what might be causing this issue?

**Comment by HouseoLogy** [comment]
Hi @reimertz,
it seems to be a network / time-out related issue on your end. Not related to M1 as such.
You could try to set `export PIP_DEFAULT_TIMEOUT=300` and retry the build process.
